const mindMap = {
  "nodes": [
    { id: '1', position: { x: 0, y: 0 }, data: { label: 'Web-приложение' }, type: 'input' },
    { id: '2', position: { x: -200, y: 200 }, data: { label: 'Клиент' } },
    { id: '3', position: { x: -400, y: 200 }, data: { label: 'Сервер' }},
    { id: '4', position: { x: -300, y: 400 }, data: { label: 'Язык программирования' } },
    { id: '5', position: { x: 400, y: 550 }, data: { label: 'Масштабируемость' } },
    { id: '6', position: { x: 200, y: 550 }, data: { label: 'Надежность' } },
    { id: '7', position: { x: 0, y: 550 }, data: { label: 'Производительность' } },
    { id: '8', position: { x: 400, y: 200 }, data: { label: 'Архитектура' }},
    { id: '9', position: { x: 750, y: 400 }, data: { label: 'Шаблон проектирования или паттерн' }, type: 'output' },
    { id: '10', position: { x: -500, y: 750 }, data: { label: 'Go' }, type: 'output'},
    { id: '11', position: { x: 700, y: 550 }, data: { label: 'Высоконагруженные системы' }},
    { id: '12', position: { x: 700, y: 800 }, data: { label: 'Микросервисная архитектура' } },
    { id: '13', position: { x: -100, y: 850 }, data: { label: 'Кеширование' }},
    { id: '14', position: { x: 200, y: 900 }, data: { label: 'Репликация' },type: 'output' },
    { id: '15', position: { x: 550, y: 900 }, data: { label: 'Шардирование' }, type: 'output' },
    { id: '16', position: { x: -350, y: 850 }, data: { label: 'Очереди' },type: 'output' },
    { id: '17', position: { x: 950, y: 1000 }, data: { label: 'Контейнеризация' }, type: 'output' },
    { id: '18', position: { x: 750, y: 1000 }, data: { label: 'Оркестрация' }, type: 'output' },
    { id: '19', position: { x: 400, y: 800 }, data: { label: 'Базы данных' } },
    { id: '20', position: { x: 400, y: 1200 }, data: { label: 'Реляционные базы данных' },type: 'output' },
    { id: '21', position: { x: 700, y: 1200 }, data: { label: 'NoSQL базы данных' }, type: 'output' },
    { id: '22', position: { x: 0, y: 1200 }, data: { label: 'In-memory базы данных' },type: 'output' },
  ],
  "edges": [
    { id: '1-2', source: '1', target: '2', label: 'Основан на' },
    { id: '1-3', source: '1', target: '3', label: 'Основан на' },
    { id: '1-8', source: '1', target: '8', label: 'Основан на' },
    { id: '1-4', source: '2', target: '4', label: 'Использует' },
    { id: '2-4', source: '2', target: '4', label: 'Использует' },
    { id: '3-4', source: '3', target: '4', label: 'Использует' },
    { id: '4-10', source: '4', target: '10', label: 'Включает' },
    { id: '8-9', source: '8', target: '9', label: 'Включает' },
    { id: '8-11', source: '8', target: '11', label: 'Включает' },
    { id: '8-5', source: '8', target: '5', label: 'Основан на' },
    { id: '8-6', source: '8', target: '6', label: 'Основан на' },
    { id: '8-7', source: '8', target: '7', label: 'Основан на' },
    { id: '5-12', source: '5', target: '12', label: 'Включает' },
    { id: '11-12', source: '11', target: '12', label: 'Основан на' },
    { id: '12-17', source: '12', target: '17', label: 'Основан на' },
    { id: '12-18', source: '12', target: '18', label: 'Основан на' },
    { id: '5-19', source: '5', target: '19', label: 'Использует' },
    { id: '6-19', source: '6', target: '19', label: 'Использует' },
    { id: '7-10', source: '7', target: '10', label: 'Взаимодействие с' },
    { id: '7-16', source: '7', target: '16', label: 'Использует' },
    { id: '7-13', source: '7', target: '13', label: 'Использует' },
    { id: '13-22', source: '13', target: '22', label: 'Применяется в' },
    { id: '19-20', source: '19', target: '20', label: 'Основан на' },
    { id: '19-14', source: '19', target: '14', label: 'Включает' },
    { id: '19-15', source: '19', target: '15', label: 'Включает' },
    { id: '19-21', source: '19', target: '21', label: 'Основан на' },
    { id: '19-22', source: '19', target: '22', label: 'Основан на' },
  ]
}


export default mindMap;


// const test = [
//   { id: '1-2', source: '1', target: '2', label: 'Взаимодействие с' },
//   { id: '1-8', source: '1', target: '8', label: 'Основан на' },
//   { id: '1-4', source: '2', target: '4', label: 'Использует' },
//   { id: '2-4', source: '2', target: '4', label: 'Использует' },
//   { id: '3-4', source: '3', target: '4', label: 'Использует' },
//   { id: '8-9', source: '8', target: '9', label: 'Включает' },
//   { id: '8-11', source: '8', target: '11', label: 'Включает' },
//   { id: '8-5', source: '8', target: '5', label: 'Основан на' },
//   { id: '8-6', source: '8', target: '6', label: 'Основан на' },
//   { id: '8-7', source: '8', target: '7', label: 'Основан на' },
//   { id: '5-12', source: '5', target: '12', label: 'Использует' },
//   { id: '5-17', source: '5', target: '17', label: 'Использует' },
//   { id: '5-19', source: '5', target: '19', label: 'Использует' },
//   { id: '6-19', source: '5', target: '19', label: 'Использует' },
//   { id: '7-10', source: '7', target: '10', label: 'Взаимодействие с' },
//   { id: '7-13', source: '7', target: '13', label: 'Взаимодействие с' },
//   { id: '13-22', source: '13', target: '22', label: 'Применяется в' },
//   { id: '19-20', source: '19', target: '20', label: 'Основан на' },
//   { id: '19-21', source: '19', target: '21', label: 'Основан на' },
//   { id: '19-22', source: '19', target: '22', label: 'Основан на' },
// ]